---
name: Build and Publish

on:
  # DEBUG ########
  pull_request:
    branches:
      - main
  ################
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: docker.io/ministryofjustice/tech-docs-github-pages-publisher@sha256:26b720c51b12f13b91d35b4447acbb21f437cfd94e36e1581ea631955ea616ba # v3.0.2
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build
        id: build
        run: |
          /scripts/deploy.sh

      - name: Upload Pages Artifact
        id: upload_pages_artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          name: github-pages
          path: docs/

  publish:
    needs: build
    name: Publish
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy_pages.outputs.page_url }}
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        id: deploy_pages
        uses: actions/deploy-pages@87c3283f01cd6fe19a0ab93a23b2f6fcba5a8e42 # v4.0.3
